variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

stages:
  - prepare_stage
  - match_stage
  - tests_stage
  - build_stage
  - merge_request_stage

before_script:
  - cd WatchLater

prepare_stage:
  stage: prepare_stage
  script:
    - bundle install
    - bundle exec pod install
  only:
    - develop
    - prod
    - merge_requests
    - /^hotfix-dev-([0-9, .])+/
    - /^hotfix-prod-([0-9, .])+/

match_stage:
  stage: match_stage
  script:
    - bundle exec fastlane ios match_stage
  only:
    - release
    - debug
    - merge_requests

tests_stage:
  stage: tests_stage
  script:
    - bundle install
    - bundle exec pod install
    - swiftgen config run --config ./WatchLater/Resources/swiftgen.yml
    - fastlane ios tests_stage
  only:
    - develop
    - prod
    - /^hotfix-dev-([0-9, .])+/
    - /^hotfix-prod-([0-9, .])+/

build_dev_stage:
  stage: build_stage
  script:
    - bundle install
    - bundle exec pod install
    - swiftgen config run --config ./WatchLater/Resources/swiftgen.yml
    - fastlane ios build_dev_stage
    - fastlane ios testflight_dev_stage
  only:
    - /^hotfix-dev-([0-9, .])+/

build_prod_stage:
  stage: build_stage
  script:
    - bundle install
    - bundle exec pod install
    - swiftgen config run --config ./WatchLater/Resources/swiftgen.yml
    - fastlane ios buld_prod_stage
    - fastlane ios testflight_prod_stage
  only:
    - prod
    - /^hotfix-prod-([0-9, .])+/

merge_request_stage:
  stage: merge_request_stage
  script:
    - cd
    - cd CommandLineTool
    - swift run CommandLineTool $CI_PROJECT_ID\|\|$CI_PROJECT_TITLE\|\|$CI_PROJECT_URL\|\|$GITLAB_USER_ID\|\|$GITLAB_USER_NAME\|\|$GITLAB_USER_LOGIN\|\|$CI_MERGE_REQUEST_IID\|\|$CI_MERGE_REQUEST_TITLE\|\|$CI_COMMIT_MESSAGE
  only:
    - merge_requests
