# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

def common_pods
  use_frameworks!
  pod "SnapKit"
  pod "SwiftGen"
  pod 'Alamofire', '~> 5.4'
  pod 'KeychainSwift'
  pod 'Kingfisher', '~> 6.2.0'
  pod 'MemoryLeakTracker'
  pod 'TKGrid', git: 'git@git.technokratos.com:ios/tkgrid.git'
end

target 'WatchLater-Kirillov_Dev' do
  use_frameworks!
  common_pods
#  target 'WatchLater-Kirillov_Dev' do
#    inherit! :search_paths
#  end
end

target 'WatchLater-Kirillov_Prod' do
  use_frameworks!
  common_pods
end


