# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

def common_pods
  use_frameworks!
  pod "SnapKit"
  pod "SwiftGen"
  pod "KeychainSwift"
end

target 'swifty-protein' do
  use_frameworks!
  common_pods
end
